---
title: 'DS202: Final Project Report'
author: 'Group 4: MyTien Kien, Tanner Dunn, Saketh Jonnadula, Ryan Pate'
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Description of Data**


### **Questions Raised**


### **Pipeline for Obtaining/Cleaning Dataset**


### **Data Wrangling and Visualization**


### **Answers for Questions Raised**

**1.** Does the popularity depend on he year it was released?


**2.** Does the popularity of a song depend on the danceability or energy?


**3.** What were the 5 most popular songs in 2020? How do these songs compare to the top 5 in 2010?


**4.** Analyze how song trends such a danceability, energy, loudness, etc... changed throughout each year.


**5.** What is the relationship between the acosticness and the tempo of a song?


**6.** Are explicit songs more popular than non-explicit songs?


**7.** Who are the most popular one hit wonders?


**8.** How has Post Malone's (Tanner's favorite artist) popularity changed over the past few years?


**9.** What are/were the most popular genres in the past century?


### **Conclusion**



### **Contribution Statement**

Overall, everyone contributed to helping making the questions for analysis. We helped each other when someone was stuck on how to do a question and/or analysis.


**MyTien Kien**

MyTien is the team coordinator for Group 4. She made sure everyone had and did their part in the overall analysis/final project. She made sure that the slides were nicely done and easy to read. MyTien was in charge questions 3 and 4.


**Saketh Jonnadula**

Saketh was in charge of questions 1 and 2.


**Tanner Dunn**

Tanner was in charge of questions 7, 8, and 9.


**Ryan Pate**

Ryan was in charge of questions 5 and 6.

